{{- range $name, $resource := .Values.hosts }}
---
apiVersion: premiscale.com/v1alpha1
kind: Host
metadata:
  {{- include "premiscale-crds.metadata" (dict "root" $ "name" $name "resource" $resource) | nindent 2 }}
spec:
  {{- toYaml $resource.spec | nindent 2 }}
{{- end }}
