// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v7.35.1
// source: templates.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TemplateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateRequest) Reset() {
	*x = TemplateRequest{}
	mi := &file_templates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateRequest) ProtoMessage() {}

func (x *TemplateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_templates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateRequest.ProtoReflect.Descriptor instead.
func (*TemplateRequest) Descriptor() ([]byte, []int) {
	return file_templates_proto_rawDescGZIP(), []int{0}
}

func (x *TemplateRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Taint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Effect        string                 `protobuf:"bytes,3,opt,name=effect,proto3" json:"effect,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Taint) Reset() {
	*x = Taint{}
	mi := &file_templates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Taint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taint) ProtoMessage() {}

func (x *Taint) ProtoReflect() protoreflect.Message {
	mi := &file_templates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taint.ProtoReflect.Descriptor instead.
func (*Taint) Descriptor() ([]byte, []int) {
	return file_templates_proto_rawDescGZIP(), []int{1}
}

func (x *Taint) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Taint) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Taint) GetEffect() string {
	if x != nil {
		return x.Effect
	}
	return ""
}

type TemplateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Labels        map[string]string      `protobuf:"bytes,1,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Capacity      map[string]string      `protobuf:"bytes,2,rep,name=capacity,proto3" json:"capacity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Allocatable   map[string]string      `protobuf:"bytes,3,rep,name=allocatable,proto3" json:"allocatable,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Taints        []*Taint               `protobuf:"bytes,4,rep,name=taints,proto3" json:"taints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateResponse) Reset() {
	*x = TemplateResponse{}
	mi := &file_templates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateResponse) ProtoMessage() {}

func (x *TemplateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_templates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateResponse.ProtoReflect.Descriptor instead.
func (*TemplateResponse) Descriptor() ([]byte, []int) {
	return file_templates_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateResponse) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *TemplateResponse) GetCapacity() map[string]string {
	if x != nil {
		return x.Capacity
	}
	return nil
}

func (x *TemplateResponse) GetAllocatable() map[string]string {
	if x != nil {
		return x.Allocatable
	}
	return nil
}

func (x *TemplateResponse) GetTaints() []*Taint {
	if x != nil {
		return x.Taints
	}
	return nil
}

var File_templates_proto protoreflect.FileDescriptor

const file_templates_proto_rawDesc = "" +
	"\n" +
	"\x0ftemplates.proto\x12\x1fpremiscale.clusterautoscaler.v1\"!\n" +
	"\x0fTemplateRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x05Taint\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06effect\x18\x03 \x01(\tR\x06effect\"\xa4\x04\n" +
	"\x10TemplateResponse\x12U\n" +
	"\x06labels\x18\x01 \x03(\v2=.premiscale.clusterautoscaler.v1.TemplateResponse.LabelsEntryR\x06labels\x12[\n" +
	"\bcapacity\x18\x02 \x03(\v2?.premiscale.clusterautoscaler.v1.TemplateResponse.CapacityEntryR\bcapacity\x12d\n" +
	"\vallocatable\x18\x03 \x03(\v2B.premiscale.clusterautoscaler.v1.TemplateResponse.AllocatableEntryR\vallocatable\x12>\n" +
	"\x06taints\x18\x04 \x03(\v2&.premiscale.clusterautoscaler.v1.TaintR\x06taints\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rCapacityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a>\n" +
	"\x10AllocatableEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012y\n" +
	"\tTemplates\x12l\n" +
	"\x03Get\x120.premiscale.clusterautoscaler.v1.TemplateRequest\x1a1.premiscale.clusterautoscaler.v1.TemplateResponse\"\x00B>Z<github.com/premiscale/premiscale/cluster-autoscaler/protocolb\x06proto3"

var (
	file_templates_proto_rawDescOnce sync.Once
	file_templates_proto_rawDescData []byte
)

func file_templates_proto_rawDescGZIP() []byte {
	file_templates_proto_rawDescOnce.Do(func() {
		file_templates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_templates_proto_rawDesc), len(file_templates_proto_rawDesc)))
	})
	return file_templates_proto_rawDescData
}

var file_templates_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_templates_proto_goTypes = []any{
	(*TemplateRequest)(nil),  // 0: premiscale.clusterautoscaler.v1.TemplateRequest
	(*Taint)(nil),            // 1: premiscale.clusterautoscaler.v1.Taint
	(*TemplateResponse)(nil), // 2: premiscale.clusterautoscaler.v1.TemplateResponse
	nil,                      // 3: premiscale.clusterautoscaler.v1.TemplateResponse.LabelsEntry
	nil,                      // 4: premiscale.clusterautoscaler.v1.TemplateResponse.CapacityEntry
	nil,                      // 5: premiscale.clusterautoscaler.v1.TemplateResponse.AllocatableEntry
}
var file_templates_proto_depIdxs = []int32{
	3, // 0: premiscale.clusterautoscaler.v1.TemplateResponse.labels:type_name -> premiscale.clusterautoscaler.v1.TemplateResponse.LabelsEntry
	4, // 1: premiscale.clusterautoscaler.v1.TemplateResponse.capacity:type_name -> premiscale.clusterautoscaler.v1.TemplateResponse.CapacityEntry
	5, // 2: premiscale.clusterautoscaler.v1.TemplateResponse.allocatable:type_name -> premiscale.clusterautoscaler.v1.TemplateResponse.AllocatableEntry
	1, // 3: premiscale.clusterautoscaler.v1.TemplateResponse.taints:type_name -> premiscale.clusterautoscaler.v1.Taint
	0, // 4: premiscale.clusterautoscaler.v1.Templates.Get:input_type -> premiscale.clusterautoscaler.v1.TemplateRequest
	2, // 5: premiscale.clusterautoscaler.v1.Templates.Get:output_type -> premiscale.clusterautoscaler.v1.TemplateResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_templates_proto_init() }
func file_templates_proto_init() {
	if File_templates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_templates_proto_rawDesc), len(file_templates_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_templates_proto_goTypes,
		DependencyIndexes: file_templates_proto_depIdxs,
		MessageInfos:      file_templates_proto_msgTypes,
	}.Build()
	File_templates_proto = out.File
	file_templates_proto_goTypes = nil
	file_templates_proto_depIdxs = nil
}
