# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""
Client and server classes corresponding to protobuf-defined services.
"""
import grpc
import warnings

from . import templates_pb2 as templates__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in templates_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TemplatesStub:
    """
    Native Go code marshals Kubernetes Node objects for autoscaler's simulator.

    """

    def __init__(self, channel):
        """
        Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/premiscale.clusterautoscaler.v1.Templates/Get',
                request_serializer=templates__pb2.TemplateRequest.SerializeToString,
                response_deserializer=templates__pb2.TemplateResponse.FromString,
                _registered_method=True)


class TemplatesServicer:
    """
    Native Go code marshals Kubernetes Node objects for autoscaler's simulator.

    """

    def Get(self, request, context):
        """
        Missing associated documentation comment in .proto file.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemplatesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=templates__pb2.TemplateRequest.FromString,
                    response_serializer=templates__pb2.TemplateResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'premiscale.clusterautoscaler.v1.Templates', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('premiscale.clusterautoscaler.v1.Templates', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Templates:
    """
    Native Go code marshals Kubernetes Node objects for autoscaler's simulator.

    """

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/premiscale.clusterautoscaler.v1.Templates/Get',
            templates__pb2.TemplateRequest.SerializeToString,
            templates__pb2.TemplateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
