# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: templates.proto
# Protobuf Python Version: 7.35.1
"""
Generated protocol buffer code.
"""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'templates.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftemplates.proto\x12\x1fpremiscale.clusterautoscaler.v1\"\x1d\n\x0fTemplateRequest\x12\n\n\x02id\x18\x01 \x01(\t\"3\n\x05Taint\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x0e\n\x06\x65\x66\x66\x65\x63t\x18\x03 \x01(\t\"\xd9\x03\n\x10TemplateResponse\x12M\n\x06labels\x18\x01 \x03(\x0b\x32=.premiscale.clusterautoscaler.v1.TemplateResponse.LabelsEntry\x12Q\n\x08\x63\x61pacity\x18\x02 \x03(\x0b\x32?.premiscale.clusterautoscaler.v1.TemplateResponse.CapacityEntry\x12W\n\x0b\x61llocatable\x18\x03 \x03(\x0b\x32\x42.premiscale.clusterautoscaler.v1.TemplateResponse.AllocatableEntry\x12\x36\n\x06taints\x18\x04 \x03(\x0b\x32&.premiscale.clusterautoscaler.v1.Taint\x1a-\n\x0bLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a/\n\rCapacityEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x32\n\x10\x41llocatableEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32y\n\tTemplates\x12l\n\x03Get\x12\x30.premiscale.clusterautoscaler.v1.TemplateRequest\x1a\x31.premiscale.clusterautoscaler.v1.TemplateResponse\"\x00\x42>Z<github.com/premiscale/premiscale/cluster-autoscaler/protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'templates_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z<github.com/premiscale/premiscale/cluster-autoscaler/protocol'
  _globals['_TEMPLATERESPONSE_LABELSENTRY']._loaded_options = None
  _globals['_TEMPLATERESPONSE_LABELSENTRY']._serialized_options = b'8\001'
  _globals['_TEMPLATERESPONSE_CAPACITYENTRY']._loaded_options = None
  _globals['_TEMPLATERESPONSE_CAPACITYENTRY']._serialized_options = b'8\001'
  _globals['_TEMPLATERESPONSE_ALLOCATABLEENTRY']._loaded_options = None
  _globals['_TEMPLATERESPONSE_ALLOCATABLEENTRY']._serialized_options = b'8\001'
  _globals['_TEMPLATEREQUEST']._serialized_start=52
  _globals['_TEMPLATEREQUEST']._serialized_end=81
  _globals['_TAINT']._serialized_start=83
  _globals['_TAINT']._serialized_end=134
  _globals['_TEMPLATERESPONSE']._serialized_start=137
  _globals['_TEMPLATERESPONSE']._serialized_end=610
  _globals['_TEMPLATERESPONSE_LABELSENTRY']._serialized_start=464
  _globals['_TEMPLATERESPONSE_LABELSENTRY']._serialized_end=509
  _globals['_TEMPLATERESPONSE_CAPACITYENTRY']._serialized_start=511
  _globals['_TEMPLATERESPONSE_CAPACITYENTRY']._serialized_end=558
  _globals['_TEMPLATERESPONSE_ALLOCATABLEENTRY']._serialized_start=560
  _globals['_TEMPLATERESPONSE_ALLOCATABLEENTRY']._serialized_end=610
  _globals['_TEMPLATES']._serialized_start=612
  _globals['_TEMPLATES']._serialized_end=733
# @@protoc_insertion_point(module_scope)
